spring:
  profiles:
    active:
    - dev  # 默认状态下
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-ahf-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-ahf-test
# 保存格式为UTF-8格式